### PR TITLE
Fixed typo in README

### PR DESCRIPTION
**Pull request by thewilloftheshadow**

### CODE REVIEW

**Comment by zastrixarundell** [comment]
Thanks! But could you change the commit title to a different one which expresses what is done exactly? At least `Fixed typo` (`Fixed typo in README` would be perfect).

Edit:

An yes, rather than writing spaghetti code, I wrote spaghetti README!

**Comment by thewilloftheshadow** [comment]
ahaha its always one or the other (:

Is that better?

**Comment by zastrixarundell** [comment]
Yeah this one is better but to keep the git log clean, I'll squash those commits into a single with a meaningful title!

**Comment by zastrixarundell** [comment]
Oh and a general note @thewilloftheshadow, you can do `git commit --amend -m "New commit message."` to change the name of the previous existing commit. No need to create a new one.

**Pull request merged**
